# Example train configs for example models 
  
train:  
  2d_mtlsd_to_affs:
    setup_dir: "models/2d_mtlsd_to_affs"
    voxel_size: [50, 2, 2]
    sigma: 80
    max_iterations: 10000
    out_dir: "models/2d_mtlsd_to_affs"
    save_checkpoints_every: 1000
    save_snapshots_every: 1000
