# Example train configs for example models 
 
3d_affs_from_2d_affs:
  setup_dir: "models/3d_affs_from_2d_affs"
  voxel_size: [50, 8, 8]
  sigma: 80
  max_iterations: 10000
  out_dir: "models/3d_affs_from_2d_affs"
  save_checkpoints_every: 1000
  save_snapshots_every: 1000

3d_affs_from_2d_lsd:
  setup_dir: "models/3d_affs_from_2d_lsd"
  voxel_size: [50, 8, 8]
  sigma: 80
  max_iterations: 10000
  out_dir: "models/3d_affs_from_2d_lsd"
  save_checkpoints_every: 1000
  save_snapshots_every: 1000

3d_affs_from_2d_mtlsd:
  setup_dir: "models/3d_affs_from_2d_mtlsd"
  voxel_size: [50, 8, 8]
  sigma: 80
  max_iterations: 10000
  out_dir: "models/3d_affs_from_2d_mtlsd"
  save_checkpoints_every: 1000
  save_snapshots_every: 1000

3d_affs_from_3d_lsd:
  setup_dir: "models/3d_affs_from_3d_lsd"
  voxel_size: [50, 8, 8]
  sigma: 80
  max_iterations: 10000
  out_dir: "models/3d_affs_from_3d_lsd"
  save_checkpoints_every: 1000
  save_snapshots_every: 1000
