# Example blockwise segmentation config 
  
db: # PostgreSQL Graph Database config
  db_name: "example_db"
  db_host: "localhost"
  db_user: "user"
  db_password: "password"
  db_port: 5432
  nodes_table: "nodes"
  edges_table: "edges"
  
processing:
  extract_fragments:
    affs_file: "data/example_volume.zarr"
    affs_dataset: "predictions/3d_affs_10000_from_20000"
    fragments_file: "data/example_volume.zarr"
    fragments_dataset: "post/fragments"
    fragments_in_xy: true
    background_mask: false
    mask_thresh: 0.5
    min_seed_distance: 15
    epsilon_agglomerate: 0.0
    filter_fragments: 0.05
    replace_sections: null
    mask_file: null
    mask_dataset: null
    roi_offset: null
    roi_shape: null
    block_size: null
    context: null
    num_workers: 10
  
  agglomerate:
    affs_file: "data/example_volume.zarr"
    affs_dataset: "predictions/3d_affs_10000_from_20000"
    fragments_file: "data/example_volume.zarr"
    fragments_dataset: "post/fragments"
    merge_function: "mean"
    roi_offset: null
    roi_shape: null
    block_size: null
    context: null
    num_workers: 1
  
  find_segments:
    fragments_file: "data/example_volume.zarr"
    fragments_dataset: "post/fragments"
    lut_dir: "post/luts"
    roi_offset: null
    roi_shape: null
    thresholds_minmax: [0, 1]
    thresholds_step: 0.05
    merge_function: "mean"
    num_workers: 4
  
  extract_segmentation:
    fragments_file: "data/example_volume.zarr"
    fragments_dataset: "post/fragments"
    lut_dir: "post/luts"
    seg_file: "data/example_volume.zarr"
    seg_dataset: "post/segmentations"
    thresholds: [0.3,0.4,0.5]
    merge_function: "mean"
    roi_offset: null
    roi_shape: null
    block_size: null
    num_workers: 400
